stages:
  - lint
  - build

lint:
  stage: lint
  image: alpinelinux/apkbuild-lint-tools:latest
  script:
    - changed-aports $CI_MERGE_REQUEST_TARGET_BRANCH_NAME | lint
  allow_failure: true
  only:
    - merge_requests
  tags:
    - docker-alpine
    - x86_64

.build:
  stage: build
  image: alpinelinux/alpine-gitlab-ci:latest
  script:
    - build.sh
  only:
    - merge_requests

build-x86_64:
  extends: .build
  tags:
    - docker-alpine
    - ci-build
    - x86_64

build-x86:
  extends: .build
  image:
    name: alpinelinux/alpine-gitlab-ci:latest-x86
    entrypoint: ["linux32", "sh", "-c"]
  tags:
    - docker-alpine
    - ci-build
    - x86

build-ppc64le:
  extends: .build
  tags:
    - docker-alpine
    - ci-build
    - ppc64le

build-aarch64:
  extends: .build
  artifacts:
    name: MR${CI_MERGE_REQUEST_ID}_aarch64
  tags:
    - docker-alpine
    - ci-build
    - aarch64
